<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/1200px-Pandas_logo.svg.png">

In [49]:
'''
What is Pandas?
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

Why Use Pandas?
Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.


Pandas : Powerful for data analysis

Pandas stands for “Python Data Analysis Library”

one of the most preferred and widely used tools in Data munging / Wrangling


Data wrangling —also called data cleaning, data remediation, 
or data munging —refers to a variety of processes designed to transform raw data into more readily used formats

'''

'\nWhat is Pandas?\nPandas is a Python library used for working with data sets.\n\nIt has functions for analyzing, cleaning, exploring, and manipulating data.\n\nWhy Use Pandas?\nPandas allows us to analyze big data and make conclusions based on statistical theories.\n\nPandas can clean messy data sets, and make them readable and relevant.\n\nRelevant data is very important in data science.\n\n\nPandas : Powerful for data analysis\n\nPandas stands for “Python Data Analysis Library”\n\none of the most preferred and widely used tools in Data munging / Wrangling\n\n\nData wrangling —also called data cleaning, data remediation, \nor data munging —refers to a variety of processes designed to transform raw data into more readily used formats\n\n'


<img src="https://static.javatpoint.com/tutorial/pandas/images/python-pandas-dataframe.png">

In [50]:
#!pip install pandas
import pandas as pd
import numpy as np

In [51]:
'''
What is a Series?
A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.
'''
s1 = pd.Series([23,24,25,12,32])
s1

0    23
1    24
2    25
3    12
4    32
dtype: int64

<img src="https://1.bp.blogspot.com/-AkAiqQBMhvM/XJiYR2xWg-I/AAAAAAAAAIo/wXoFEgnKbhQbpEy_o5XxAYY5uA0y97hOQCLcBGAs/w1200-h630-p-k-no-nu/pandas-powerful-data-analysis-tools-for-python-13-638.jpg">

In [52]:
s2 = pd.Series([23,45,67,12,34],index = ['a','b','c','d','e'])
s2

a    23
b    45
c    67
d    12
e    34
dtype: int64

In [53]:
s3 = pd.Series([23,45,67,12,34],index = ['a','b','c','d','e'],dtype = 'float')
s3

a    23.0
b    45.0
c    67.0
d    12.0
e    34.0
dtype: float64

### creation of Series using dictionary

In [54]:
s4 = pd.Series({'e':65,'f':43,'c':45})
s4

e    65
f    43
c    45
dtype: int64

### DataFrame
What is a DataFrame?
A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

<img src="https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png">

In [55]:
d1 = pd.DataFrame([43,54,65,76])
d1

    0
0  43
1  54
2  65
3  76

In [56]:
d2 = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]])
d2

   0  1  2
0  2  3  4
1  4  5  6
2  1  2  3

In [57]:
d2 = pd.DataFrame(s2)  #converting series into dataframe
d2

    0
a  23
b  45
c  67
d  12
e  34

In [58]:
d3  = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns =['a','b','c'])
d3

   a  b  c
0  2  3  4
1  4  5  6
2  1  2  3

In [59]:
d3  = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns =['a','b','c'],index = ['x','y','z'])
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

### creating DataFrame from list of dictionaries

In [60]:
dic = [{'alex':1,'joe':2},{'ema':5,'dora':10,'alice':20},{'ema':5,'dora':10,'alice':20}]    
pd.DataFrame(dic,index=['a','b','c'])

   alex  joe  ema  dora  alice
a   1.0  2.0  NaN   NaN    NaN
b   NaN  NaN  5.0  10.0   20.0
c   NaN  NaN  5.0  10.0   20.0

### DataFrame operations

In [61]:
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

In [62]:
print(d3['a'])
print(d3['b'])

x    2
y    4
z    1
Name: a, dtype: int64
x    3
y    5
z    2
Name: b, dtype: int64

In [63]:
d3['d']=d3['a']*d3['b']
d3['e']=d3['a']+d3['d']
d3

   a  b  c   d   e
x  2  3  4   6   8
y  4  5  6  20  24
z  1  2  3   2   3

In [64]:
pop = d3.pop('b') 
d3

   a  c   d   e
x  2  4   6   8
y  4  6  20  24
z  1  3   2   3

In [65]:
d3

   a  c   d   e
x  2  4   6   8
y  4  6  20  24
z  1  3   2   3

In [66]:
del d3['d']

In [67]:
d3

   a  c   e
x  2  4   8
y  4  6  24
z  1  3   3

In [68]:
d3.pop('a')
d3

   c   e
x  4   8
y  6  24
z  3   3

In [69]:
d3.insert(1,'new1',d3['c']) #(loc,col,data)
d3

   c  new1   e
x  4     4   8
y  6     6  24
z  3     3   3

In [71]:
d = {'c': 1, 'new1': 33, 'e': 22}
df11 = pd.concat([d3, pd.DataFrame([d])], ignore_index=True)
df11

   c  new1   e
0  4     4   8
1  6     6  24
2  3     3   3
3  1    33  22

In [91]:
import numpy as np
d4 = pd.DataFrame({'abc':np.random.randint(2,6,size=(15)),'bcd':np.random.randint(4,10,size=(15))})
d4

    abc  bcd
0     4    8
1     5    5
2     2    7
3     3    4
4     4    7
5     3    4
6     2    9
7     3    4
8     5    7
9     4    8
10    4    8
11    3    6
12    3    6
13    2    4
14    3    5

In [92]:
d4.head()

   abc  bcd
0    4    8
1    5    5
2    2    7
3    3    4
4    4    7

In [93]:
d4.tail()

    abc  bcd
10    4    8
11    3    6
12    3    6
13    2    4
14    3    5

In [94]:
'''
Info About the Data
The DataFrames object has a method called info(),that gives you more information about the data set.'''
d4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     15 non-null     int32
 1   bcd     15 non-null     int32
dtypes: int32(2)
memory usage: 252.0 bytes

<img src="https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2019/02/pandas-loc-get-specific-column-syntax.png">

In [95]:
d4

    abc  bcd
0     4    8
1     5    5
2     2    7
3     3    4
4     4    7
5     3    4
6     2    9
7     3    4
8     5    7
9     4    8
10    4    8
11    3    6
12    3    6
13    2    4
14    3    5

In [ ]:
d4

In [96]:
d4.loc[2:4,['abc','bcd']]

   abc  bcd
2    2    7
3    3    4
4    4    7

In [97]:
d4.loc[[3,4,1],['abc','bcd']]

   abc  bcd
3    3    4
4    4    7
1    5    5

In [98]:
d4.loc[1,'abc'] #loc[row name,colname]

np.int32(5)

In [101]:
d4

    abc  bcd
0     4    8
1     5    5
2     2    7
3     3    4
4     4    7
5     3    4
6     2    9
7     3    4
8     5    7
9     4    8
10    4    8
11    3    6
12    3    6
13    2    4
14    3    5

<img src='https://www.marsja.se/wp-content/uploads/2019/09/pandas_select_row_by_index_iloc.png'>

In [105]:
d4.iloc[4,1]  #[row index,column index]

np.int32(7)

In [107]:
d4.iloc[2:7,[0,1]]

   abc  bcd
2    2    7
3    3    4
4    4    7
5    3    4
6    2    9

In [108]:
d4

    abc  bcd
0     4    8
1     5    5
2     2    7
3     3    4
4     4    7
5     3    4
6     2    9
7     3    4
8     5    7
9     4    8
10    4    8
11    3    6
12    3    6
13    2    4
14    3    5

In [109]:
d4.abc

0     4
1     5
2     2
3     3
4     4
5     3
6     2
7     3
8     5
9     4
10    4
11    3
12    3
13    2
14    3
Name: abc, dtype: int32

In [110]:
d4.abc.values # data frame . column .values

array([4, 5, 2, 3, 4, 3, 2, 3, 5, 4, 4, 3, 3, 2, 3], dtype=int32)

In [112]:
d4['sub'] = d4.abc.values - 1 - d4.bcd.values
d4

    abc  bcd  sub
0     4    8   -5
1     5    5   -1
2     2    7   -6
3     3    4   -2
4     4    7   -4
5     3    4   -2
6     2    9   -8
7     3    4   -2
8     5    7   -3
9     4    8   -5
10    4    8   -5
11    3    6   -4
12    3    6   -4
13    2    4   -3
14    3    5   -3

In [125]:
a = [['rk',102,15000],['rama',103,20000],['krishna',104,25000]]
dfl = pd.DataFrame(a,columns = ['name','id','salary'])
dfl

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000

In [126]:
y=dfl[dfl.salary>=20000]
print(y)
y[['id','salary']]

      name   id  salary
1     rama  103   20000
2  krishna  104   25000

    id  salary
1  103   20000
2  104   25000

In [127]:
new_row = pd.DataFrame([{
    'name': 'sajan',
    'id': 105,
    'salary': 30000
}])

dfl = pd.concat([dfl, new_row], ignore_index=True)

print(dfl)

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3    sajan  105   30000

In [128]:
new_row2 = pd.DataFrame([{
    'name' : np.nan,
    'id' : 105,
    'salary' : 30000
}])

dfl = pd.concat([dfl,new_row2],ignore_index = True)
dfl

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3    sajan  105   30000
4      NaN  105   30000

In [129]:
dfl.isnull()

    name     id  salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4   True  False   False

In [130]:
dfl.isnull().sum()

name      1
id        0
salary    0
dtype: int64

In [131]:
dfl.dropna()

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3    sajan  105   30000

In [132]:
dfl

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3    sajan  105   30000
4      NaN  105   30000

In [133]:
dfl.fillna(value = 'abc')

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3    sajan  105   30000
4      abc  105   30000

In [134]:
dfl

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3    sajan  105   30000
4      NaN  105   30000

In [135]:
dfl.drop([0],axis=0,inplace=True)
dfl

      name   id  salary
1     rama  103   20000
2  krishna  104   25000
3    sajan  105   30000
4      NaN  105   30000


### Groupby

<img src="https://th.bing.com/th/id/OIP.h5V2-wp2jL4Ip5FTRd6ThQAAAA?pid=ImgDet&rs=1">

In [136]:
df = pd.DataFrame({'Animal' : ['Falcon', 'Falcon','Parrot', 'Parrot'],'Max Speed' : [380., 370., 24., 26.]})
df

   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [137]:
df.groupby(['Animal']).mean()

        Max Speed
Animal
Falcon      375.0
Parrot       25.0

In [151]:
import pandas as pd
df_csv = pd.read_csv('data.csv')
df_csv

     id     name       city           course  age   salary  gender
0   101  Abhinav  Hyderabad           Python   22  45000.0    Male
1   102    Sajan  Bangalore             Java   25  52000.0    Male
2   103    Rahul    Chennai           Python   24  48000.0    Male
3   104    Priya  Hyderabad     Data Science   23  55000.0  Female
4   105   Anjali       Pune           Python   26      NaN  Female
5   106    Kiran  Bangalore             Java   28  65000.0    Male
6   107    Sneha    Chennai     Data Science   27  72000.0  Female
7   108    Arjun     Mumbai  Web Development   22  40000.0    Male
8   109    Meena        NaN           Python   29  68000.0  Female
9   110   Vikram      Delhi             Java   31  75000.0    Male
10  111     Ravi  Hyderabad  Web Development   24  46000.0    Male
11  112    Divya     Mumbai           Python   25  58000.0  Female
12  113     Aman        NaN     Data Science   30  82000.0    Male
13  114    Pooja       Pune              NaN   27  63000.0  Female
14  115   Naveen    Chennai           Python   23  44000.0    Male
15  116  Lakshmi  Bangalore     Data Science   26  70000.0  Female
16  117      Sai  Hyderabad             Java   29  67000.0    Male
17  118   Swathi      Delhi  Web Development   24  49000.0  Female
18  119    Rohit     Mumbai           Python   28  61000.0    Male
19  120     Neha        NaN     Data Science   25  59000.0  Female

In [154]:
df_csv.columns
df_csv.isnull().sum()

id        0
name      0
city      3
course    1
age       0
salary    1
gender    0
dtype: int64

In [144]:
df_csv['city'].values

array(['Hyderabad', 'Bangalore', 'Chennai', 'Hyderabad', 'Pune',
       'Bangalore', 'Chennai', 'Mumbai', nan, 'Delhi', 'Hyderabad',
       'Mumbai', nan, 'Pune', 'Chennai', 'Bangalore', 'Hyderabad',
       'Delhi', 'Mumbai', nan], dtype=object)

In [145]:
df_csv['city'].isnull().sum()

np.int64(3)

In [147]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.random.randn(4, 3),
    columns=['col1', 'col2', 'col3']
)

print(df)
print('\n')

for key, value in df.items():
    print(key)
    print(value)
    print('\n')

       col1      col2      col3
0  0.849387 -1.179070 -0.779036
1 -0.731299  0.538350 -1.749536
2 -1.032327 -0.129077 -1.105725
3 -0.491676 -0.871290 -0.598986


col1
0    0.849387
1   -0.731299
2   -1.032327
3   -0.491676
Name: col1, dtype: float64


col2
0   -1.179070
1    0.538350
2   -0.129077
3   -0.871290
Name: col2, dtype: float64


col3
0   -0.779036
1   -1.749536
2   -1.105725
3   -0.598986
Name: col3, dtype: float64

In [148]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.random.randn(4, 3),
    columns=['col1', 'col2', 'col3']
)


print(df)
print('\n')
for row in df.iterrows():
   print(row)
   print('\n')

       col1      col2      col3
0  0.214081 -1.105061 -0.816511
1 -1.418361 -0.002835 -0.570356
2 -0.845260  1.310348  2.256852
3  0.535025 -0.217409  0.182297


(0, col1    0.214081
col2   -1.105061
col3   -0.816511
Name: 0, dtype: float64)


(1, col1   -1.418361
col2   -0.002835
col3   -0.570356
Name: 1, dtype: float64)


(2, col1   -0.845260
col2    1.310348
col3    2.256852
Name: 2, dtype: float64)


(3, col1    0.535025
col2   -0.217409
col3    0.182297
Name: 3, dtype: float64)

In [ ]:
#pd.Series?

In [149]:
# Transpose
df.T

             0         1         2         3
col1  0.214081 -1.418361 -0.845260  0.535025
col2 -1.105061 -0.002835  1.310348 -0.217409
col3 -0.816511 -0.570356  2.256852  0.182297

### Get Dummies

In [155]:
import pandas as pd

data = {'firstname': ['Arun', 'Jebu', 'Venkat', 'Rekha', 'Majid','Mohsin'], 
        'lastname': ['Kumar', 'Jacob', 'Raghavan', 'Singh', 'Khan','Khan'], 
        'employmenttype': ['Service', 'Business', 'Student', 'Service', 'Business','Business'],
        'country' :['India','USA','USA','Sweden','Australia','Germany']}


df = pd.DataFrame(data, columns = ['firstname','lastname','employmenttype','country'])

print(df)

  firstname  lastname employmenttype    country
0      Arun     Kumar        Service      India
1      Jebu     Jacob       Business        USA
2    Venkat  Raghavan        Student        USA
3     Rekha     Singh        Service     Sweden
4     Majid      Khan       Business  Australia
5    Mohsin      Khan       Business    Germany

In [156]:
df1 = pd.get_dummies(df['employmenttype'])
df2 = pd.get_dummies(df['country'])
print(df1)
print(df2)

   Business  Service  Student
0     False     True    False
1      True    False    False
2     False    False     True
3     False     True    False
4      True    False    False
5      True    False    False
   Australia  Germany  India  Sweden    USA
0      False    False   True   False  False
1      False    False  False   False   True
2      False    False  False   False   True
3      False    False  False    True  False
4       True    False  False   False  False
5      False     True  False   False  False

In [ ]:
df

In [157]:
frames = [df,df1,df2]
result = pd.concat(frames,axis=1)
result

,firstname,lastname,employmenttype,country,Business,Service,Student,Australia,Germany,India,Sweden,USA
0,Arun,Kumar,Service,India,False,True,False,False,False,True,False,False
1,Jebu,Jacob,Business,USA,True,False,False,False,False,False,False,True
2,Venkat,Raghavan,Student,USA,False,False,True,False,False,False,False,True
3,Rekha,Singh,Service,Sweden,False,True,False,False,False,False,True,False
4,Majid,Khan,Business,Australia,True,False,False,True,False,False,False,False
5,Mohsin,Khan,Business,Germany,True,False,False,False,True,False,False,False

## concatination

In [158]:
import pandas as pd
india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [159]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [160]:
df = pd.concat([india_weather, us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [161]:
# ignore index
df = pd.concat([india_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [162]:
# concatinate using keys
df = pd.concat([india_weather, us_weather], keys=["india", "us"])
df

             city  temperature  humidity
india 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
us    0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [ ]:
'''
Finding Relationships
A great aspect of the Pandas module is the corr() method.

The corr() method calculates the relationship between each column in your data set.
'''

In [163]:
df=pd.read_csv('data.csv')
df.corr()

ValueError: could not convert string to float: 'Abhinav'

In [ ]:
'''
Perfect Correlation:
We can see that "Duration" and "Duration" got the number 1.000000, 
which makes sense, each column always has a perfect relationship with itself.

Good Correlation:
"Duration" and "Calories" got a 0.922721 correlation, which is a very good correlation, 
and we can predict that the longer you work out, the more calories you burn, and the other way around:
if you burned a lot of calories, you probably had a long work out.

Bad Correlation:
"Duration" and "Maxpulse" got a 0.009403 correlation, which is a very bad correlation, 
meaning that we can not predict the max pulse by just looking at the duration of the work out, and vice versa.

'''

In [ ]:
import pandas as pd  
emp = {"Name": ["Parker", "Smith", "William", "Parker"],  
"Age": [21, 32, 29, 21]}  
info = pd.DataFrame(emp)  
print(info)
print("--------------------")
info = info.drop_duplicates()  
print(info)

<h1>Apply<h1>

In [ ]:
import pandas as pd
def calc_sum(kiran):
    return kiran+1
data = {
  "x": [50, 40, 30],
  "y": [300, 1112, 42]
}
df = pd.DataFrame(data)
print(df)
x = df.apply(calc_sum)
print(x)

In [164]:
#explore sql joins
import pandas as pd
data1 = {
  "name": ["Sally", "Mary", "John"],
  "age": [50, 40, 30]
}

data2 = {
  "name": ["Sally", "Peter", "Micky"],
  "age": [77, 44, 22]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1)
print(df2)
print("...........")
newdf = df1.merge(df2, how='right')
print(newdf)

    name  age
0  Sally   50
1   Mary   40
2   John   30
    name  age
0  Sally   77
1  Peter   44
2  Micky   22
...........
    name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [165]:
print(df1)
print(df2)

    name  age
0  Sally   50
1   Mary   40
2   John   30
    name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [166]:
df3=pd.merge(df1,df2,on="name",how="outer")
df3

    name  age_x  age_y
0   John   30.0    NaN
1   Mary   40.0    NaN
2  Micky    NaN   22.0
3  Peter    NaN   44.0
4  Sally   50.0   77.0

In [167]:
df3=pd.merge(df1,df2,on="name",how="left")
df3

    name  age_x  age_y
0  Sally     50   77.0
1   Mary     40    NaN
2   John     30    NaN

In [168]:
df3=pd.merge(df1,df2,on="name",how="right")
df3

    name  age_x  age_y
0  Sally   50.0     77
1  Peter    NaN     44
2  Micky    NaN     22

In [169]:
df3=pd.merge(df1,df2,on="name",how="inner")
df3

    name  age_x  age_y
0  Sally     50     77