In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\abhin\anaconda3\lib\site-packages (2.2.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\abhin\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abhin\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abhin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\abhin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
s1 = pd.Series([23,24,25,12,32])
s1

0    23
1    24
2    25
3    12
4    32
dtype: int64

In [4]:
s2 = pd.Series([23,45,67,12,34],index = ['a','b','c','d','e'])
s2

a    23
b    45
c    67
d    12
e    34
dtype: int64

In [5]:
s4 = pd.Series({'e':65,'f':43,'c':45})
s4

e    65
f    43
c    45
dtype: int64

In [6]:
d1 = pd.DataFrame([43,54,65,76])
d1

    0
0  43
1  54
2  65
3  76

In [7]:
d2 = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]])
d2

   0  1  2
0  2  3  4
1  4  5  6
2  1  2  3

In [8]:
d3  = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns =['a','b','c'])
d3

   a  b  c
0  2  3  4
1  4  5  6
2  1  2  3

In [20]:
d3  = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns =['a','b','c'],index = ['x','y','z'])
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

In [21]:
dic = [{'alex':1,'joe':2},{'ema':5,'dora':10,'alice':20},{'ema':5,'dora':10,'alice':20}]    
pd.DataFrame(dic,index=['a','b','c'])

   alex  joe  ema  dora  alice
a   1.0  2.0  NaN   NaN    NaN
b   NaN  NaN  5.0  10.0   20.0
c   NaN  NaN  5.0  10.0   20.0

In [22]:
#accessing

print(d3['a'])
print(d3['b'])


d3['d']=d3['a']*d3['b']
d3['e']=d3['a']+d3['d']
d3

x    2
y    4
z    1
Name: a, dtype: int64
x    3
y    5
z    2
Name: b, dtype: int64

   a  b  c   d   e
x  2  3  4   6   8
y  4  5  6  20  24
z  1  2  3   2   3

In [24]:
print(d3.columns)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [25]:
pop = d3.pop('a') 
d3

   b  c   d   e
x  3  4   6   8
y  5  6  20  24
z  2  3   2   3

In [28]:
del d3['e']

In [29]:
d3

   b  c
x  3  4
y  5  6
z  2  3

In [30]:
d3.insert(1,'new1',d3['c']) #(loc,col,data)
d3

   b  new1  c
x  3     4  4
y  5     6  6
z  2     3  3

In [31]:
d = {'b': 1, 'new1': 33, 'c': 22}
df11 = pd.concat([d3, pd.DataFrame([d])], ignore_index=True)
df11

   b  new1   c
0  3     4   4
1  5     6   6
2  2     3   3
3  1    33  22

In [32]:
import numpy as np
d4 = pd.DataFrame({'abc':np.random.randint(2,6,size=(15)),'bcd':np.random.randint(4,10,size=(15))})
d4

    abc  bcd
0     2    8
1     2    8
2     2    4
3     5    5
4     4    9
5     5    4
6     3    4
7     4    8
8     3    6
9     5    5
10    3    4
11    4    5
12    2    4
13    5    7
14    2    5

In [33]:
d4.head()
d4.tail()

    abc  bcd
10    3    4
11    4    5
12    2    4
13    5    7
14    2    5

In [34]:
d4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     15 non-null     int32
 1   bcd     15 non-null     int32
dtypes: int32(2)
memory usage: 252.0 bytes

In [35]:
d4

    abc  bcd
0     2    8
1     2    8
2     2    4
3     5    5
4     4    9
5     5    4
6     3    4
7     4    8
8     3    6
9     5    5
10    3    4
11    4    5
12    2    4
13    5    7
14    2    5

In [36]:
d4.loc[2:4,['abc','bcd']]

   abc  bcd
2    2    4
3    5    5
4    4    9

In [37]:
d4.loc[[3,4,1],['abc','bcd']]

   abc  bcd
3    5    5
4    4    9
1    2    8

In [38]:
d4.loc[1,'abc'] #loc[row name,colname]

np.int32(2)

In [39]:
d4

    abc  bcd
0     2    8
1     2    8
2     2    4
3     5    5
4     4    9
5     5    4
6     3    4
7     4    8
8     3    6
9     5    5
10    3    4
11    4    5
12    2    4
13    5    7
14    2    5

In [41]:
d4.iloc[4,1]  #[row index,column index]

np.int32(9)

In [42]:

d4.iloc[2:7,[0,1]]

   abc  bcd
2    2    4
3    5    5
4    4    9
5    5    4
6    3    4

In [43]:
d4.abc

0     2
1     2
2     2
3     5
4     4
5     5
6     3
7     4
8     3
9     5
10    3
11    4
12    2
13    5
14    2
Name: abc, dtype: int32

In [44]:
d4.abc.values # data frame . column .values

array([2, 2, 2, 5, 4, 5, 3, 4, 3, 5, 3, 4, 2, 5, 2], dtype=int32)

In [45]:
d4['sub'] = d4.abc.values - 1 - d4.bcd.values
d4

    abc  bcd  sub
0     2    8   -7
1     2    8   -7
2     2    4   -3
3     5    5   -1
4     4    9   -6
5     5    4    0
6     3    4   -2
7     4    8   -5
8     3    6   -4
9     5    5   -1
10    3    4   -2
11    4    5   -2
12    2    4   -3
13    5    7   -3
14    2    5   -4

In [47]:
import numpy as np
df = pd.read_csv("data.csv")
print(df)

     id     name       city           course  age   salary  gender
0   101  Abhinav  Hyderabad           Python   22  45000.0    Male
1   102    Sajan  Bangalore             Java   25  52000.0    Male
2   103    Rahul    Chennai           Python   24  48000.0    Male
3   104    Priya  Hyderabad     Data Science   23  55000.0  Female
4   105   Anjali       Pune           Python   26      NaN  Female
5   106    Kiran  Bangalore             Java   28  65000.0    Male
6   107    Sneha    Chennai     Data Science   27  72000.0  Female
7   108    Arjun     Mumbai  Web Development   22  40000.0    Male
8   109    Meena        NaN           Python   29  68000.0  Female
9   110   Vikram      Delhi             Java   31  75000.0    Male
10  111     Ravi  Hyderabad  Web Development   24  46000.0    Male
11  112    Divya     Mumbai           Python   25  58000.0  Female
12  113     Aman        NaN     Data Science   30  82000.0    Male
13  114    Pooja       Pune              NaN   27  63000.0  Female
14  115   Naveen    Chennai           Python   23  44000.0    Male
15  116  Lakshmi  Bangalore     Data Science   26  70000.0  Female
16  117      Sai  Hyderabad             Java   29  67000.0    Male
17  118   Swathi      Delhi  Web Development   24  49000.0  Female
18  119    Rohit     Mumbai           Python   28  61000.0    Male
19  120     Neha        NaN     Data Science   25  59000.0  Female

In [49]:
print("-----------------------------------")
print(df.head())

print("-----------------------------------")
print(df.tail())


print("-----------------------------------")
print(df.shape)


print("-----------------------------------")
print(df.columns)

print("-----------------------------------")
print(df.info())

print("-----------------------------------")
print(df.describe())

-----------------------------------
    id     name       city        course  age   salary  gender
0  101  Abhinav  Hyderabad        Python   22  45000.0    Male
1  102    Sajan  Bangalore          Java   25  52000.0    Male
2  103    Rahul    Chennai        Python   24  48000.0    Male
3  104    Priya  Hyderabad  Data Science   23  55000.0  Female
4  105   Anjali       Pune        Python   26      NaN  Female
-----------------------------------
     id     name       city           course  age   salary  gender
15  116  Lakshmi  Bangalore     Data Science   26  70000.0  Female
16  117      Sai  Hyderabad             Java   29  67000.0    Male
17  118   Swathi      Delhi  Web Development   24  49000.0  Female
18  119    Rohit     Mumbai           Python   28  61000.0    Male
19  120     Neha        NaN     Data Science   25  59000.0  Female
-----------------------------------
(20, 7)
-----------------------------------
Index(['id', 'name', 'city', 'course', 'age', 'salary', 'gender'], dtype='object')
-----------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20 non-null     int64
 1   name    20 non-null     object
 2   city    17 non-null     object
 3   course  19 non-null     object
 4   age     20 non-null     int64
 5   salary  19 non-null     float64
 6   gender  20 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.2+ KB
None
-----------------------------------
              id        age        salary
count   20.00000  20.000000     19.000000
mean   110.50000  25.900000  58894.736842
std      5.91608   2.653697  11817.570425
min    101.00000  22.000000  40000.000000
25%    105.75000  24.000000  48500.000000
50%    110.50000  25.500000  59000.000000
75%    115.25000  28.000000  67500.000000
max    120.00000  31.000000  82000.000000

In [50]:
df['name']

0     Abhinav
1       Sajan
2       Rahul
3       Priya
4      Anjali
5       Kiran
6       Sneha
7       Arjun
8       Meena
9      Vikram
10       Ravi
11      Divya
12       Aman
13      Pooja
14     Naveen
15    Lakshmi
16        Sai
17     Swathi
18      Rohit
19       Neha
Name: name, dtype: object

In [51]:
df[['name', 'city', 'salary']]

       name       city   salary
0   Abhinav  Hyderabad  45000.0
1     Sajan  Bangalore  52000.0
2     Rahul    Chennai  48000.0
3     Priya  Hyderabad  55000.0
4    Anjali       Pune      NaN
5     Kiran  Bangalore  65000.0
6     Sneha    Chennai  72000.0
7     Arjun     Mumbai  40000.0
8     Meena        NaN  68000.0
9    Vikram      Delhi  75000.0
10     Ravi  Hyderabad  46000.0
11    Divya     Mumbai  58000.0
12     Aman        NaN  82000.0
13    Pooja       Pune  63000.0
14   Naveen    Chennai  44000.0
15  Lakshmi  Bangalore  70000.0
16      Sai  Hyderabad  67000.0
17   Swathi      Delhi  49000.0
18    Rohit     Mumbai  61000.0
19     Neha        NaN  59000.0

In [52]:
df.loc[5]

id              106
name          Kiran
city      Bangalore
course         Java
age              28
salary      65000.0
gender         Male
Name: 5, dtype: object

In [53]:
df.loc[2:5]

    id    name       city        course  age   salary  gender
2  103   Rahul    Chennai        Python   24  48000.0    Male
3  104   Priya  Hyderabad  Data Science   23  55000.0  Female
4  105  Anjali       Pune        Python   26      NaN  Female
5  106   Kiran  Bangalore          Java   28  65000.0    Male

In [54]:


df.loc[[2, 5, 8], ['name', 'salary']]

    name   salary
2  Rahul  48000.0
5  Kiran  65000.0
8  Meena  68000.0

In [55]:
df.iloc[2]

id            103
name        Rahul
city      Chennai
course     Python
age            24
salary    48000.0
gender       Male
Name: 2, dtype: object

In [56]:
df.iloc[0:3]

    id     name       city  course  age   salary gender
0  101  Abhinav  Hyderabad  Python   22  45000.0   Male
1  102    Sajan  Bangalore    Java   25  52000.0   Male
2  103    Rahul    Chennai  Python   24  48000.0   Male

In [57]:
df.iloc[2:6, 0:3]

    id    name       city
2  103   Rahul    Chennai
3  104   Priya  Hyderabad
4  105  Anjali       Pune
5  106   Kiran  Bangalore

In [60]:
print(df[df['salary'] > 60000])
print("-------------------------------------")
print(df[df['course'] == 'Python'])

     id     name       city        course  age   salary  gender
5   106    Kiran  Bangalore          Java   28  65000.0    Male
6   107    Sneha    Chennai  Data Science   27  72000.0  Female
8   109    Meena        NaN        Python   29  68000.0  Female
9   110   Vikram      Delhi          Java   31  75000.0    Male
12  113     Aman        NaN  Data Science   30  82000.0    Male
13  114    Pooja       Pune           NaN   27  63000.0  Female
15  116  Lakshmi  Bangalore  Data Science   26  70000.0  Female
16  117      Sai  Hyderabad          Java   29  67000.0    Male
18  119    Rohit     Mumbai        Python   28  61000.0    Male
-------------------------------------
     id     name       city  course  age   salary  gender
0   101  Abhinav  Hyderabad  Python   22  45000.0    Male
2   103    Rahul    Chennai  Python   24  48000.0    Male
4   105   Anjali       Pune  Python   26      NaN  Female
8   109    Meena        NaN  Python   29  68000.0  Female
11  112    Divya     Mumbai  Python   25  58000.0  Female
14  115   Naveen    Chennai  Python   23  44000.0    Male
18  119    Rohit     Mumbai  Python   28  61000.0    Male

In [61]:
df[(df['salary'] > 50000) & (df['age'] > 25)]

     id     name       city        course  age   salary  gender
5   106    Kiran  Bangalore          Java   28  65000.0    Male
6   107    Sneha    Chennai  Data Science   27  72000.0  Female
8   109    Meena        NaN        Python   29  68000.0  Female
9   110   Vikram      Delhi          Java   31  75000.0    Male
12  113     Aman        NaN  Data Science   30  82000.0    Male
13  114    Pooja       Pune           NaN   27  63000.0  Female
15  116  Lakshmi  Bangalore  Data Science   26  70000.0  Female
16  117      Sai  Hyderabad          Java   29  67000.0    Male
18  119    Rohit     Mumbai        Python   28  61000.0    Male

In [62]:
print(df.isnull())
print("-------------------")

print(df.isnull().sum())
print("----------------------")

       id   name   city  course    age  salary  gender
0   False  False  False   False  False   False   False
1   False  False  False   False  False   False   False
2   False  False  False   False  False   False   False
3   False  False  False   False  False   False   False
4   False  False  False   False  False    True   False
5   False  False  False   False  False   False   False
6   False  False  False   False  False   False   False
7   False  False  False   False  False   False   False
8   False  False   True   False  False   False   False
9   False  False  False   False  False   False   False
10  False  False  False   False  False   False   False
11  False  False  False   False  False   False   False
12  False  False   True   False  False   False   False
13  False  False  False    True  False   False   False
14  False  False  False   False  False   False   False
15  False  False  False   False  False   False   False
16  False  False  False   False  False   False   False
17  False  False  False   False  False   False   False
18  False  False  False   False  False   False   False
19  False  False   True   False  False   False   False
-------------------
id        0
name      0
city      3
course    1
age       0
salary    1
gender    0
dtype: int64
----------------------

In [63]:
df['salary'] = df['salary'].fillna(0)

In [64]:

print(df.isnull().sum())
print("----------------------")

id        0
name      0
city      3
course    1
age       0
salary    0
gender    0
dtype: int64
----------------------

In [65]:
df.dropna()

     id     name       city           course  age   salary  gender
0   101  Abhinav  Hyderabad           Python   22  45000.0    Male
1   102    Sajan  Bangalore             Java   25  52000.0    Male
2   103    Rahul    Chennai           Python   24  48000.0    Male
3   104    Priya  Hyderabad     Data Science   23  55000.0  Female
4   105   Anjali       Pune           Python   26      0.0  Female
5   106    Kiran  Bangalore             Java   28  65000.0    Male
6   107    Sneha    Chennai     Data Science   27  72000.0  Female
7   108    Arjun     Mumbai  Web Development   22  40000.0    Male
9   110   Vikram      Delhi             Java   31  75000.0    Male
10  111     Ravi  Hyderabad  Web Development   24  46000.0    Male
11  112    Divya     Mumbai           Python   25  58000.0  Female
14  115   Naveen    Chennai           Python   23  44000.0    Male
15  116  Lakshmi  Bangalore     Data Science   26  70000.0  Female
16  117      Sai  Hyderabad             Java   29  67000.0    Male
17  118   Swathi      Delhi  Web Development   24  49000.0  Female
18  119    Rohit     Mumbai           Python   28  61000.0    Male

In [66]:
df.groupby('city')

In [67]:
df.groupby('city')['salary'].sum()

city
Bangalore    187000.0
Chennai      164000.0
Delhi        124000.0
Hyderabad    213000.0
Mumbai       159000.0
Pune          63000.0
Name: salary, dtype: float64

In [68]:
df.sort_values('salary')

     id     name       city           course  age   salary  gender
4   105   Anjali       Pune           Python   26      0.0  Female
7   108    Arjun     Mumbai  Web Development   22  40000.0    Male
14  115   Naveen    Chennai           Python   23  44000.0    Male
0   101  Abhinav  Hyderabad           Python   22  45000.0    Male
10  111     Ravi  Hyderabad  Web Development   24  46000.0    Male
2   103    Rahul    Chennai           Python   24  48000.0    Male
17  118   Swathi      Delhi  Web Development   24  49000.0  Female
1   102    Sajan  Bangalore             Java   25  52000.0    Male
3   104    Priya  Hyderabad     Data Science   23  55000.0  Female
11  112    Divya     Mumbai           Python   25  58000.0  Female
19  120     Neha        NaN     Data Science   25  59000.0  Female
18  119    Rohit     Mumbai           Python   28  61000.0    Male
13  114    Pooja       Pune              NaN   27  63000.0  Female
5   106    Kiran  Bangalore             Java   28  65000.0    Male
16  117      Sai  Hyderabad             Java   29  67000.0    Male
8   109    Meena        NaN           Python   29  68000.0  Female
15  116  Lakshmi  Bangalore     Data Science   26  70000.0  Female
6   107    Sneha    Chennai     Data Science   27  72000.0  Female
9   110   Vikram      Delhi             Java   31  75000.0    Male
12  113     Aman        NaN     Data Science   30  82000.0    Male